FROM python:3.8

# 
WORKDIR /code

RUN mkdir /code/models

# 
COPY ./requirements_cpu.txt /code/requirements_cpu.txt
# 
RUN pip install --no-cache-dir --upgrade -r /code/requirements_cpu.txt
# 
COPY ./app /code/app
COPY ./run.sh /code/run.sh
#
ENTRYPOINT ["sh", "run.sh"]


